apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-nodejs
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-nodejs-deployment
  lastScaleTime: 
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
