apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-nodejs-ingressre
  labels:
    app: hello-nodejs
  annotations:
    # ingress.bluemix.net/rewrite-path: "serviceName=hello-nodejs rewrite=/;serviceName=pacman rewrite=/"
    ingress.bluemix.net/rewrite-path: "serviceName=pacman rewrite=/"
    # ex) ingress.bluemix.net/rewrite-path: "serviceName=app rewrite=/"
    # ingress.bluemix.net/redirect-to-https: "True" 
spec:
  tls:
  - hosts:
    - dev.sato-cluster.jp-tok.containers.appdomain.cloud # ibmcloud ks cluster-get mycluster --json | jq '.ingressHostname'
    secretName: sato-cluster # ibmcloud ks cluster-get mycluster --json | jq '.ingressSecretName'
  rules:
  - host: dev.sato-cluster.jp-tok.containers.appdomain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-nodejs
          servicePort: 80
      - path: /pacman
        backend:
          serviceName: pacman
          servicePort: 80
